title: Kelley.ink
author:
  name: 'Kelley McAllister'
  email: kelley@kelley.ink
taxonomies:
  - category
  - tag
metadata:
  description: 'Kelley is a writer, a marketer, a teller of stories…above all, a communicator. Based in Portland, OR.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
