title: Services
'@extends': default

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            columns:
              fields:
                column1:
                  fields:
                    name:
                      default: modular/services
                      '@data-options': '\Grav\Common\Page\Pages::modularTypes'
            overrides:
              fields:
                header.template:
                  default: modular/services
                  '@data-options': '\Grav\Common\Page\Pages::modularTypes'
        content:
          fields:
            uploads:
              label: Page Media (first one will be displayed next to your content)
            header.image_align:
              type: select
              label: Image position
              classes: fancy
              default: left
              options:
                'left': 'Left'
                'right': 'Right'
              type:
services:
    itemcolone:
        servicename:
        icon:
        subtitle:
    itemcoltwo:
        servicename:
        icon:
        subtitle:
    itemcolthree:
        servicename:
        icon:
        subtitle:
    itemcolfour:
        servicename:
        icon:
        subtitle:
    itemcolfive:
        servicename:
        icon:
        subtitle:
    itemcolsix:
        servicename:
        icon:
        subtitle:
